spring.application.name=Bank-App
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/chomubank}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:7953}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false